### ISSUE TITLE
nb-configuration.xml: удалить из проекта и добавить в .gitignore

### ISSUE THREAD

**Issue by php-coder** [AleksSPb/Spring-demo-App1#10]
К сожалению, я не объяснил в #7 то, что настройки редактора и прочие вещи, используемые одним разработчиком, но которые не нужны остальным, в git коммитить не надо. Поэтому, наверное, сейчас тут появился файл `nb-configuration.xml`...

**Comment by AleksSPb** [comment]
:)
Добавлю.
Закончился ключ на IDEA, поставил себе NetBeans, который и создал этот файл.

16 сентября 2015 г., 22:25 пользователь Slava Semushin <
notifications@github.com> написал:

> К сожалению, я не объяснил в #7
> https://github.com/AleksSPb/Spring-demo-App1/issues/7 то, что настройки
> редактора и прочие вещи, используемые одним разработчиком, но которые не
> нужны остальным, в git коммитить не надо. Поэтому, наверное, сейчас тут
> появился файл nb-configuration.xml...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AleksSPb/Spring-demo-App1/issues/10.

## 

Всего наилучшего, Пархоменко Александр

**Comment by AleksSPb** [comment]
исправил

**Comment by php-coder** [comment]
А чем IDEA Community Edition не подходит? Я в ней работаю несколько лет и вполне доволен.

**Comment by AleksSPb** [comment]
Подходит.
Просто на курсах дали ключик от ультимайт, и он недавно закончился.
А сайт jetBrain что-то тормозил и не удавалось скачать дистрибутив
коммунити, теперь скачал,буду пользоваться ею.

2015-09-17 9:05 GMT+03:00 Slava Semushin notifications@github.com:

> А чем IDEA Community Edition не подходит? Я в ней работаю несколько лет и
> вполне доволен.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AleksSPb/Spring-demo-App1/issues/10#issuecomment-140977478
> .

## 

Всего наилучшего, Пархоменко Александр
