### ISSUE TITLE
Выводить приветствие на русском

### ISSUE THREAD

**Issue by php-coder** [AleksSPb/Spring-demo-App1#3]
Попробуйте вывести не `Hello World`, а что-нибудь на русском, например, `Здравствуй мир!`.

**Comment by AleksSPb** [comment]
Вывел. Добавил в Мавен определение страницы и resource.setDefaultEncoding("UTF-8");

**Comment by php-coder** [comment]
> Вывел. Добавил в Мавен определение страницы и resource.setDefaultEncoding("UTF-8");

Пока не могу проревьювить, т.к. вы не запушили и мне ваши изменения не видны.
