### ISSUE TITLE
Обновить Jetty плагин

### ISSUE THREAD

**Issue by php-coder** [AleksSPb/Spring-demo-App1#4]
Сейчас используется очень старая версия плагина. Предлагаю обновить до более новой. См. http://www.eclipse.org/jetty/documentation/current/jetty-maven-plugin.html

**Comment by AleksSPb** [comment]
Спасибо, буду разбираться.
Сам плагин я скачал, только пока не разобрался с IDEA.

7 сентября 2015 г., 20:11 пользователь Slava Semushin <
notifications@github.com> написал:

> Сейчас используется очень старая версия плагина. Предлагаю обновить до
> более новой. См.
> http://www.eclipse.org/jetty/documentation/current/jetty-maven-plugin.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AleksSPb/Spring-demo-App1/issues/4.

## 

Всего наилучшего, Пархоменко Александр

**Comment by AleksSPb** [comment]
что-то не видит он у меня новую, пока не понимаю почему
<plugin>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-maven-plugin</artifactId>
  <version>9.3.1-SNAPSHOT</version>
</plugin>
а со старой работало нормально, пока оставил работающий вариант

**Comment by php-coder** [comment]
Начните с того, чтобы не использовать снапшотную версию.

**Comment by AleksSPb** [comment]
Установил 9.3.4RC
