### ISSUE TITLE
Исправить сборку

### ISSUE THREAD

**Issue by php-coder** [AleksSPb/Spring-demo-App1#9]
Похоже, что вы забыли закоммитить какие-то файлы:

```
Spring-demo-App1 > mvn clean jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring-demo-App1 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Spring-demo-App1 ---
[INFO] Deleting C:\cygwin64\home\v.semushin\Spring-demo-App1\target
[INFO]
[INFO] >>> jetty-maven-plugin:8.1.16.v20140903:run (default-cli) @ Spring-demo-App1 >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Spring-demo-App1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\cygwin64\home\v.semushin\Spring-demo-App1\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ Spring-demo-App1 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to C:\cygwin64\home\v.semushin\Spring-demo-App1\target\classes
[INFO] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java: C:\cygwin64\home\v.semushin\Spring-demo-App1\src\main\java\com\springapp\mvc\controller\HelloController.java uses unchecked or unsafe operations.
[INFO] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[3,31] package com.springapp.mvc.model does not exist
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAO.java:[3,31] package com.springapp.mvc.model does not exist
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[26,12] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[42,17] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAO.java:[8,5] cannot find symbol
  symbol:   class People
  location: interface com.springapp.mvc.DAO.PeopleDAO
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAO.java:[10,10] cannot find symbol
  symbol:   class People
  location: interface com.springapp.mvc.DAO.PeopleDAO
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[54,66] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[56,16] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl.PeopleMapper
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[3,31] package com.springapp.mvc.model does not exist
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[39,44] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[81,66] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[83,16] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController.PeopleMapper
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[32,9] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[48,14] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[57,13] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl.PeopleMapper
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[57,33] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.DAO.PeopleDAOImpl.PeopleMapper
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[64,42] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[77,14] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[84,13] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController.PeopleMapper
[ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[84,33] cannot find symbol
  symbol:   class People
  location: class com.springapp.mvc.controller.HelloController.PeopleMapper
[INFO] 20 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by AleksSPb** [comment]
Да, не все файлы
Пробую сделать новый коммит, а идея пишет вот такое:
Error:pathspec 'src/main/java/com/springapp/mvc/model/People.java' did not
match any file(s) known to git.

Буду разбираться.

2015-09-10 13:31 GMT+03:00 Slava Semushin notifications@github.com:

> Spring-demo-App1 > mvn clean jetty:run
> [INFO] Scanning for projects...
> [INFO]
> [INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Spring-demo-App1 1.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Spring-demo-App1 ---
> [INFO] Deleting C:\cygwin64\home\v.semushin\Spring-demo-App1\target
> [INFO]
> [INFO] >>> jetty-maven-plugin:8.1.16.v20140903:run (default-cli) @ Spring-demo-App1 >>>
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Spring-demo-App1 ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory C:\cygwin64\home\v.semushin\Spring-demo-App1\src\main\resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ Spring-demo-App1 ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 7 source files to C:\cygwin64\home\v.semushin\Spring-demo-App1\target\classes
> [INFO] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java: C:\cygwin64\home\v.semushin\Spring-demo-App1\src\main\java\com\springapp\mvc\controller\HelloController.java uses unchecked or unsafe operations.
> [INFO] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java: Recompile with -Xlint:unchecked for details.
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[3,31] package com.springapp.mvc.model does not exist
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAO.java:[3,31] package com.springapp.mvc.model does not exist
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[26,12] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[42,17] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAO.java:[8,5] cannot find symbol
>   symbol:   class People
>   location: interface com.springapp.mvc.DAO.PeopleDAO
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAO.java:[10,10] cannot find symbol
>   symbol:   class People
>   location: interface com.springapp.mvc.DAO.PeopleDAO
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[54,66] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[56,16] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl.PeopleMapper
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[3,31] package com.springapp.mvc.model does not exist
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[39,44] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[81,66] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[83,16] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController.PeopleMapper
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[32,9] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[48,14] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[57,13] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl.PeopleMapper
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/DAO/PeopleDAOImpl.java:[57,33] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.DAO.PeopleDAOImpl.PeopleMapper
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[64,42] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[77,14] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[84,13] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController.PeopleMapper
> [ERROR] /C:/cygwin64/home/v.semushin/Spring-demo-App1/src/main/java/com/springapp/mvc/controller/HelloController.java:[84,33] cannot find symbol
>   symbol:   class People
>   location: class com.springapp.mvc.controller.HelloController.PeopleMapper
> [INFO] 20 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AleksSPb/Spring-demo-App1/issues/9.

## 

Всего наилучшего, Пархоменко Александр

**Comment by AleksSPb** [comment]
Добавлены файлы
